#!/bin/ksh
#---------------------------------------------------------------------
# Script: MAIN_SCR
#---------------------------------------------------------------------
#
# Purpose: Calls fcm extract on a local machine and build
#          and/or run commands on a remote machine
#
# Created from umui vn8.5
#---------------------------------------------------------------------


#---------------------------------------------
# User defined environment variables
#---------------------------------------------
export UM_RAD_SPECTRAL_GL=$UMDIR/vn$VN/ctldata/spectral
export STARTDUMPS=/projects/access/data/input_dumps/GA6

#---------------------------------------------
# Job specific variables
#---------------------------------------------
export RUNID=vablf
export USERID=$USER
export DATAW=/short/$PROJECT/$USER/$RUNID

UM_ROUTDIR=/short/$PROJECT/$USER/UM_ROUTDIR/$USERID/$RUNID
UM_RDATADIR=/short/$PROJECT/$USER/$RUNID

export UM_SVN_URL=fcm:um-tr
export UM_SVN_BIND=fcm:um_dev/vn8.5/local_changes/src/configs/bindings
export UM_CONTAINER=$UM_SVN_BIND/container.cfg@HEAD

export PROCESSED_DIR=/home/599/jxs599/umui_jobs/vablf
. $PROCESSED_DIR/COMP_SWITCHES

# Loop through all submodels and set up RUN_COMPILE
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run_compile=false
for item
in UMSCRIPTS UMATMOS UMRECON NEMO CICE NEMO_CICE UM_NEMO_CICE
do
  eval compval=\$COMP_${item}
  if test $compval = "true" ; then
    run_compile=true
    break
  fi
done

RUN_COMPILE=$run_compile

#---------------------------------------------
# Do Extract if compilation was requested
#---------------------------------------------

RC=0
if test $RUN_COMPILE = "true" ; then
   echo
   echo MAIN_SCR: Calling Extract ...
   $PROCESSED_DIR/EXTR_SCR
   RC=$?
   if test $RC -eq 0 ; then
      echo MAIN_SCR: Extract OK
   else
      echo MAIN_SCR: Extract failed >&2
      echo MAIN_SCR stopped with return code $RC
      exit
   fi
fi

#---------------------------------------------
#   Submit to compile or/and run
#---------------------------------------------

if test $RC -eq 0 ; then
   RUN_FILE=stage_1_submit
   echo
   echo MAIN_SCR: Calling UMSUBMIT ...

     $PROCESSED_DIR/UMSUBMIT \
     -h raijin.nci.org.au \
     -u ${USERID} \
     -m 4 \
      ${RUNID}    \
      ${RUN_FILE}

   RC=$?
   if test $RC -eq 0 ; then
     echo MAIN_SCR: Submit OK
   else
     echo MAIN_SCR: Submit failed >&2
   fi
fi 

exit 0

#EOF  
