#!/bin/ksh
#PBS -l walltime=200
#PBS -l ncpus=256
#PBS -l mem=512000mb
#PBS -j oe
#PBS -o /home/599/jxs599/um_output/vablf000.vablf.d14154.t140624.leave



# Load default programming environment for PBS Pro
. ~access/umdir/vn8.5/environment

/home/599/jxs599/umui_runs/vablf-154140614/umuisubmit_run 
